### ISSUE TITLE
How to Create Custom Group Chat 

### ISSUE THREAD

**Issue by syedhassanfaraz** [rohith/ChatterClub#1]
How to Create Custom Group Chat in this code .

Can you guide?

**Comment by brandedoutcast** [comment]
Nope, I was just exploring SignalR when I wrote this 😫 & I've no further plans 😒 

Although creating groups should be fairly simple if you go through the [docs](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/working-with-groups)
